version: "3"
services:
  ml-app:
    build: .
    ports:
      - "8080:80"
    environment:
      - PROFILE=prod
      - VARIABLE_NAME=server
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"